### ISSUE TITLE
Can't save settings, got error '0,65' is not valid floating point value.

### ISSUE THREAD

**Issue by disazoz** [TrueOpenVR/TrueOpenVR-Core#1]
My system is: 
Windows 7 x64, en_US locale. 
Probably that happens because of my system use dot (.) as decimal separator.

**Comment by r57zone** [comment]
Fixed, please try again in [updated app](https://github.com/TrueOpenVR/TrueOpenVR-Core/releases/).

**Comment by disazoz** [comment]
Yes, this error is gone but looks like that nothing changed. Have no steamvr.vrsettings or driver files installed. Do I have to do it by manual, copy files and write steamvr.vrsettings?

**Comment by r57zone** [comment]
With the program [TrueOpenVR SteamVR](https://github.com/TrueOpenVR/SteamVR-TrueOpenVR/releases) you can install the driver, settings are taken from TrueOpenVR headset profile.
