### ISSUE TITLE
Use LG VR360 without Vagle VRD-1000

### ISSUE THREAD

**Issue by RomSand** [TrueOpenVR/TrueOpenVR-Core#2]
Hi...
 I don't know if it's ok to write in Russian so I'll better do it in English.
 As I know LG VR can be directly connected to pc to USB Type-C  without adapter I wanted to know if the image will be rotated or not ?
And would internal tracking will work corectly for the games ?

Thanks.

**Comment by r57zone** [comment]
Hi, I do not have the LG 360 VR, so I do not know. You can rotate the display in Windows.

Internal tracking will work the same everywhere, but you need to write a 64 bit driver for it. Here is an [sample driver](https://github.com/TrueOpenVR/TrueOpenVR-Drivers/blob/master/C%2B%2B/Sample/Sample/Sample.cpp).

**Comment by RomSand** [comment]
TrueOpenVR will activates the glasses ? As I know they need special data string for activation...
I saw in the description that it is also LG VR360 with Vagle VRD-1000 did someone try it ?
I'm planning to buy this glasses you can get them for 50$ easy, but whan to know if your driver will work...
Thanks.

**Comment by r57zone** [comment]
At the moment True OpenVR does not support LG 360 VR. Specifically for driver development, I do not plan to buy it yet.

**Comment by RomSand** [comment]
Did you try with CV1 ?

**Comment by r57zone** [comment]
I tried with [this drivers](https://github.com/TrueOpenVR/TrueOpenVR-Drivers).

**Comment by RomSand** [comment]
Let me understand, is it more for tracking not the video output ? FreeTrack can be used vith CV1 doe this mean it will use osulus driver ?

**Comment by r57zone** [comment]
If you need SteamVR, you need to write a driver for the LG 360 VR. Such questions can be asked by email.
