### ISSUE TITLE
PSmove install.bat file error

### ISSUE THREAD

**Issue by oivio** [TrueOpenVR/TrueOpenVR-Core#3]
Somehow I do feel it is small problem. But, here it is. 
After running this file I'm getting an error:

> The system cannot find the path specified.
> The system cannot find the path specified.
> Installed
> Press any key to continue . . .

and with admin permission: 

> The system cannot find the path specified.
> The system cannot find the path specified.
> Installed
> Press any key to continue . . .

**Comment by r57zone** [comment]
What operating system are you using? The system is 32 or 64? Do you use Windows 10 64bit?

You can manually copy the "PSMoveClient_CAPI.dll" file from "lib\x64\release" to "C:\Windows\System32" and the "PSMoveClient_CAPI.dll" file from "lib\x86\release" to the "C:\Windows\SysWOW64" folder.

**Comment by oivio** [comment]
I'm using 64 but I did do it as well manually for both. After it, I did go to settings and change to PSmove then apply. After apply I did run PSMoveServiceAdmin.exe and next GetData.exe just to see if it is working but no data was shown. Still, after it I did try to running SteamVr but nothing there. Iv can add that light balls did not light up.  
So on the end, I did think it was an install.bat problem but looks like it is something else.

**Comment by r57zone** [comment]
Have you [configured](https://www.youtube.com/watch?v=IunGVk89-TY) PSMoveService?

Probably the problem of "install.bat" in access rights, I'll try to fix it.

**Comment by oivio** [comment]
yes, I did. Currently, I'm using with drive4vr. 

Ps: Do I have to use PsmoveServiceSteamVrBridge with it?

I can add that TrueOpenVR it self-work when I use Keyboard emulation. Just PSmoveService is the main problem for me.

**Comment by r57zone** [comment]
"PsmoveServiceSteamVrBridge" do not need, you need to run the configured "PSmoveService" before use. It is configure in "PSmoveServiceConfig".

**Comment by oivio** [comment]
I did just ask since the link you did provide [configurded](https://www.youtube.com/watch?v=IunGVk89-TY) it shows as well this bridge.  Is there a difference if I do use PSmoveServiceAdmin instead PSmoveService? Anyways, why do I ask, I can check it by my self.

**Comment by r57zone** [comment]
There's just the beginning of the video where PSMoveService is being set up. PSmoveServiceAdmin is preferable, that there were no problems with the access.

**Comment by r57zone** [comment]
I removed the automatic installer. I made folders for copying in "C:\Windows" and wrote the instruction.

**Comment by oivio** [comment]
thank you, I will check it out! :)

**Comment by oivio** [comment]
After the update, I can confirm that positional, rotation tracking works. Only the buttons like triggers etc are not responsive but, should they be working? Is this thing that has to be done form PSmoveService somehow? 

Anyways, thank you. It is really amazing to see something like that working.

**Comment by r57zone** [comment]
I have not yet completed the driver to the end. At the moment, you can only track the balls. This is done so that can make controllers on Arduino, with ping pong balls and LED.

I plan to make a full driver, with full support for PS Move controllers (buttons and rotation).
