### ISSUE TITLE
PS Move orientation not correct.

### ISSUE THREAD

**Issue by ramaibrm** [TrueOpenVR/TrueOpenVR-Core#6]
Hi, the driver works very well with the positional tracking,I am using a PSMove Controller,  however my ps move orientation is not correct, and I can't find a way to fix it.

**Comment by r57zone** [comment]
Hi, are you using TrueOpenVR 0.7.2 and TrueOpenVR-SteamVR driver 0.5?
 I will fix the axes, but testing is needed

**Comment by ramaibrm** [comment]
Yes, I use the latest version of both.

**Comment by r57zone** [comment]
Are all axis wrong?
https://blog.dsky.co/wp-content/uploads/2015/05/dSky-Oculus-XYZ-YPR.jpg

[PSMoveService64.zip](https://github.com/TrueOpenVR/TrueOpenVR-Core/files/4532776/PSMoveService64.zip)
Try this, will it be correct axis?

**Comment by ramaibrm** [comment]
As I identify with the original PSMoveService64.dll that comes with TrueOpenVR 0.7.2.
The yaw is inverted (the controller yaw to the left when I yaw right)
The roll becomes pitch
the pitch is messed up and it makes the controller rolls.

The PSMoveService64.zip that you include seems not fixxing the issue.

**Comment by RamaRamesses** [comment]
The PSMoveService64.zip that you just include makes the yaw and pitch becomes mixed and even messed up, while the roll now becomes yaw.

**Comment by r57zone** [comment]
Try this (test ver 0.1)
[PSMoveService64.zip](https://github.com/TrueOpenVR/TrueOpenVR-Core/files/4532797/PSMoveService64.zip)

**Comment by ramaibrm** [comment]
> Try this (test ver 0.1)
> [PSMoveService64.zip](https://github.com/TrueOpenVR/TrueOpenVR-Core/files/4532797/PSMoveService64.zip)

the roll axes correct when it heading towards forward, once I try to orientate it to the left it becomes pitch
pitch is inverted
yaw does correct when i yaw to the right, but it eventually goes pitch down when I yaw to the left

**Comment by r57zone** [comment]
Try this (test ver 0.2)
[PSMoveService64.zip](https://github.com/TrueOpenVR/TrueOpenVR-Core/files/4532818/PSMoveService64.zip)
Centering is also needed, pick up and press on both controllers: PS button and select button

**Comment by ramaibrm** [comment]
> Try this (test ver 0.2)
> [PSMoveService64.zip](https://github.com/TrueOpenVR/TrueOpenVR-Core/files/4532818/PSMoveService64.zip)
> Centering is also needed, pick up and press on both controllers: PS button and select button

This fixed the issue!
It's now orientate correctly, thank you for you work!

**Comment by r57zone** [comment]
It is very cool! Thanks for testing. Does tracking work in all axes at 360 degrees? No problem?

**Comment by ramaibrm** [comment]
> It is very cool! Thanks for testing. Does tracking work in all axes at 360 degrees? No problem?

I have experienced no problem at all for now, but I will soon report to you if I found any problem with it.
By the way I'm using 4 PS3Eye Cams with 360 tracking.

**Comment by r57zone** [comment]
This is good, thanks for testing.
