### ISSUE TITLE
RiftCat support

### ISSUE THREAD

**Issue by wohdek21** [TrueOpenVR/TrueOpenVR-Core#8]
Hello, how can i add a riftCat solution to drivers?

**Comment by r57zone** [comment]
Hi, this is not supported

**Comment by wohdek21** [comment]
is there any solution of this problem?

**Comment by r57zone** [comment]
the driver is able to work in mode only controllers or only hmd, tuning is on youtube video
youtu.be/QCA3m4_3IJM
https://www.youtube.com/watch?v=HWtdCc_f4ww

**Comment by wohdek21** [comment]
Thanks
